# Generated by Django 5.1 on 2024-09-01 15:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_user_tags_delete_tag_user_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
