# Generated by Django 5.1 on 2024-09-01 15:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profileImage'),
        ),
    ]
